### PR TITLE
added registration page, liability terms image, added unit test

### PR DESCRIPTION
**Pull request by danieleynis**

### CODE REVIEW

**Comment by MikeOlivas** [comment]
This looks good. The only thing I would suggest is to add a "required" attribute to each of the input fields except for the "Co-signature" one.

**Comment by danieleynis** [comment]
@MikeOlivas added the required attribute to input fields

**Comment by BishoyHanna91** [comment]
It looks good but there are some data missed as the affiliation number, major. Also, I am not sure it u need to put the name of this page at the header or not. Other than that the page is perfect.

**Comment by danieleynis** [comment]
We agreed that we are not going to include that data because in the new
form they are not collecting that anymore. Also I put the name of the page
in the title block.

On Jan 27, 2018 13:52, "BishoyHanna91" <notifications@github.com> wrote:

It looks good but there are some data missed as the affiliation number,
major. Also, I am not sure it u need to put the name of this page at the
header or not. Other than that the page is perfect.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LUCCA-Capstone/LUCCA/pull/21#issuecomment-361018203>,
or mute the thread

**Comment by BishoyHanna91** [comment]
OK I see

**Pull request merged**
