### PR TITLE
consolidated tests into one folder, added nunjucks support

### PR DESCRIPTION
**Pull request by danieleynis**
added unit tests for routes, modified travis to run tests

### CODE REVIEW

**Comment by danieleynis** [comment]
Initial unit test ideas from here:
https://buddy.works/guides/how-automate-nodejs-unit-tests-with-mocha-chai

**Comment by danieleynis** [comment]
Would recommend this plugin for VSCode to help with nunjucks (.njk) files  
https://github.com/ronnidc/vscode-nunjucks

**Comment by MikeOlivas** [comment]
Good finds! Plugin for VSCode installed and unit testing page reviewed. Changes look good all-around.

**Comment by MikeOlivas** [comment]
I don't want to push the "close and comment" button before the other listed reviewers get a chance to look at the pull request, but is there somewhere else I should be giving my thumbs up?

**Comment by jstar1** [comment]
Taking a look at this now. Feel free to merge since Mike gave it the check over.

**Comment by danieleynis** [comment]
@MikeOlivas have you had a chance to run the mocha tests? you may need to install mocha globally to run it from the command line (`npm install -g mocha`). Then you would need to start up the node app and then in a separate window run `npm test` or just run `mocha` directly.

**Comment by jstar1** [comment]
`Page status
    Main page
GET / 200 7.064 ms - 13
      ✓ status
    Admin login page
GET /adminLogin 200 12.833 ms - 6004
      ✓ status
    Badge-in page
GET /badgein 200 1.421 ms - 881
      ✓ status`

Looks good to me

**Comment by MikeOlivas** [comment]
Yup; looks good to me too.
image

**Comment by jstar1** [comment]
> @MikeOlivas have you had a chance to run the mocha tests? you may need to install mocha globally to run it from the command line (npm install -g mocha). Then you would need to start up the node app and then in a separate window run npm test or just run mocha directly.

@danieleynis does he need to do this if travis-ci is doing it for him?

**Comment by danieleynis** [comment]
@jstar1 @MikeOlivas I have configured travis to run the mocha tests, but it is also good to verify the tests run on your machine also just in case.

**Comment by danieleynis** [comment]
Also running the tests on your machine can expedite the process of making sure you havent made a modification that could possibly break something instead of having to wait for travis to run the tests each time.

**Pull request merged**
