### PR TITLE
heartbeat api

### PR DESCRIPTION
**Pull request by jstar1**

### CODE REVIEW

**Comment by jstar1** [comment]
I might be having formatting problems with vs code. . Let me know I cant seem to get it right.

**Comment by jstar1** [comment]
I also excluded test in this patch because they rely on the external database

**Comment by danieleynis** [comment]
For the tab issue in VSCode in your setting make sure tab size is set to 2 and also enable this setting: `    "editor.insertSpaces": true`. Then do `Shift+Alt+F`. Should solve your problem.

**Comment by jstar1** [comment]
Yea those things are all set. It's weird because this wasnt an issue before

**Comment by jstar1** [comment]
I have test prepared for this when we figure out our db situation with travis.

**Pull request merged**
